package business.report;

import java.io.File;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;

import business.model.User;

public class ReportGeneratorHTML extends ReportGeneratorTemplate {
    @Override
    public void exportReport(String title, String subtitle, User user, String datetime)
            throws IOException {
        File f = new File("report.htm");
        BufferedWriter bw = new BufferedWriter(new FileWriter(f));
        bw.write("<html><body><h1>"+title+"</h1>");
        bw.write("<p>"+subtitle+"</p>");
        bw.write("<textarea cols=75 rows=10>");
        bw.write("Report generated by: " + user.getLogin());
        bw.newLine();
        bw.write("Date and time of generation: " + datetime);
        bw.write("</textarea>");
        bw.write("</body></html>");
        bw.close();
    }
}